# Robustness check: First, last, three search queries
As a robustness check, we compare the distribution of search query indicators between the first and last search query formulated by the respondents, as well as all three search queries combined (as presented in the paper).

In [1]:
import pandas as pd

In [2]:
# setting paths
PATH = '/Users/marieke/SearchingForBias'

### Immigration

In [3]:
im = pd.read_csv(PATH+"/data/immigration/df_analysis.csv",sep='\t')
im.shape

(1607, 172)

In [4]:
# how many specific
for e in ['SPECIFIC_1', 'SPECIFIC_2', 'SPECIFIC_3']:
    print(im[e].value_counts(normalize=True)*100)

0.0    54.387057
1.0    45.612943
Name: SPECIFIC_1, dtype: float64
1.0    63.658992
0.0    36.341008
Name: SPECIFIC_2, dtype: float64
1.0    75.35781
0.0    24.64219
Name: SPECIFIC_3, dtype: float64

In [5]:
im_names = {'DEBATE':'Debate',
         'PROBLEMS':'Problems',
         'ADMISSION':'Admission',
         'AZC':'Accommodation center',
         'HOUSING':'Housing',
         'INTEGRATION':'Integration',
         'CRIME':'Crime',
         'RACISM':'Racism',
         'ECONOMY':'Economy',
         'FINANCIAL_SUPPORT':'Financial support',
         'CULTURE_RELIGION':'Culture and religion',
         'CAUSES':'Causes',
         'POLITICS':'Politics',
         'STATISTICS':'Statistics',
         'ORIGIN':'Origin',
         'NEWS':'News'}

terms_names = {'immigrant':'Immigrant',
         'buitenlander':'Buitenlander',
         'gelukszoeker':'Gelukszoeker',
         'statushouder':'Statushouder',
         'allochtoon':'Allochtoon',
         'vluchteling':'Vluchteling',
         'expat':'Expat',
         'asielzoeker':'Asielzoeker'
        }

In [6]:
cols = list(im_names.keys())
cols1 = [c+"_1" for c in im_names.keys()]
cols3 = [c+"_3" for c in im_names.keys()]
terms = list(terms_names.keys())
terms1 = [c+"_1" for c in terms_names.keys()]
terms3 = [c+"_3" for c in terms_names.keys()]

In [7]:
def strip_last(x):
    return x[:-2]

In [8]:
# terms
tmp1 = pd.DataFrame(round(im[terms].mean()*100, 1), columns=["All"])
tmp2 = pd.DataFrame(round(im[terms1].mean()*100, 1), columns=["First only"])
tmp2.index = tmp2.index.map(strip_last)
tmp3 = pd.DataFrame(round(im[terms3].mean()*100, 1), columns=["Third only"])
tmp3.index = tmp3.index.map(strip_last)
dest = pd.concat([tmp1,tmp2,tmp3], axis=1).sort_values(by='All', ascending=False)
dest.index = dest.index.map(terms_names)
dest

               All  First only  Third only
Vluchteling   33.2        12.5        13.4
Asielzoeker   27.9        12.1        10.3
Immigrant     27.5        16.9         9.8
Buitenlander  12.2         3.4         5.5
Allochtoon     6.7         3.0         2.1
Gelukszoeker   1.9         0.4         0.8
Statushouder   1.6         0.6         0.6
Expat          1.6         0.6         0.4

In [9]:
# topics
tmp1 = pd.DataFrame(round(im[cols].mean()*100, 1), columns=["All"])
tmp2 = pd.DataFrame(round(im[cols1].mean()*100, 1), columns=["First only"])
tmp2.index = tmp2.index.map(strip_last)
tmp3 = pd.DataFrame(round(im[cols3].mean()*100, 1), columns=["Third only"])
tmp3.index = tmp3.index.map(strip_last)
des = pd.concat([tmp1,tmp2,tmp3], axis=1).sort_values(by='All', ascending=False)
des.index = des.index.map(im_names)
des

                       All  First only  Third only
Admission             27.9        14.6        19.1
Statistics            21.2        24.2        10.1
Integration           14.6        10.5         8.4
Accommodation center  12.3         4.5         7.4
Causes                 7.8         4.1         4.4
Crime                  6.5         3.3         3.6
Politics               6.3         2.7         4.6
Origin                 6.2         4.1         2.6
Housing                6.1         3.3         4.5
Culture and religion   5.5         2.7         4.2
Problems               5.2         2.6         3.0
Economy                4.2         1.5         3.5
Racism                 3.6         3.3         2.3
Debate                 3.4         3.0         2.1
Financial support      3.2         1.5         1.8
News                   2.3         1.4         1.5

In [10]:
des = des.append(dest)
des

<ipython-input-10-23f42b668441>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  des = des.append(dest)

                       All  First only  Third only
Admission             27.9        14.6        19.1
Statistics            21.2        24.2        10.1
Integration           14.6        10.5         8.4
Accommodation center  12.3         4.5         7.4
Causes                 7.8         4.1         4.4
Crime                  6.5         3.3         3.6
Politics               6.3         2.7         4.6
Origin                 6.2         4.1         2.6
Housing                6.1         3.3         4.5
Culture and religion   5.5         2.7         4.2
Problems               5.2         2.6         3.0
Economy                4.2         1.5         3.5
Racism                 3.6         3.3         2.3
Debate                 3.4         3.0         2.1
Financial support      3.2         1.5         1.8
News                   2.3         1.4         1.5
Vluchteling           33.2        12.5        13.4
Asielzoeker           27.9        12.1        10.3
Immigrant             27.5        16.9         9.8
Buitenlander          12.2         3.4         5.5
Allochtoon             6.7         3.0         2.1
Gelukszoeker           1.9         0.4         0.8
Statushouder           1.6         0.6         0.6
Expat                  1.6         0.6         0.4

### Climate change

In [11]:
cc = pd.read_csv(PATH+"/data/climate/df_analysis.csv",sep='\t')
cc.shape

(1729, 130)

In [12]:
# how many specific
for e in ['SPECIFIEK_1', 'SPECIFIEK_2', 'SPECIFIEK_3']:
    print(cc[e].value_counts(normalize=True)*100)

1.0    63.909774
0.0    36.090226
Name: SPECIFIEK_1, dtype: float64
1.0    84.499711
0.0    15.500289
Name: SPECIFIEK_2, dtype: float64
1.0    89.1845
0.0    10.8155
Name: SPECIFIEK_3, dtype: float64

In [13]:
cc_names = {'GEVOLG':'Consequences',
         'POLITIEK_BELEID':'Politics & policy',
         'INFO_STATUS_QUO':'Trends and current status',
         'MILIEU':'Environmental problems',
         'INFO_OPLOSSINGEN':'Solutions',
         'CO2':'Carbon',
         'INDIVIDUEEL_GEDRAG':'Individual behaviour',
         'ENERGIE':'Energy',
         'SCEPTICI':'Climate change denial',
         'ACTIVISME':'Activism',
         'DISCUSSIE':'Debate',
         'STIKSTOF':'Nitrogen',
         'VOEDSELINDUSTRIE':'Agriculture',
         'OORZAKEN':'Causes',
         'VERVOER':'Transport',
         'INDUSTRIE':'Industry',
         'SCEPTICI_PERSONEN':'Climate change deniers'
        }

In [14]:
cols = list(cc_names.keys())
cols1 = [c+"_1" for c in cc_names.keys()]
cols3 = [c+"_3" for c in cc_names.keys()]

In [15]:
tmp1 = pd.DataFrame(round(cc[cols].mean()*100, 1), columns=["All"])
tmp2 = pd.DataFrame(round(cc[cols1].mean()*100, 1), columns=["First only"])
tmp2.index = tmp2.index.map(strip_last)
tmp3 = pd.DataFrame(round(cc[cols3].mean()*100, 1), columns=["Third only"])
tmp3.index = tmp3.index.map(strip_last)
des2 = pd.concat([tmp1,tmp2,tmp3], axis=1).sort_values(by='All', ascending=False)
des2.index = des2.index.map(cc_names)
des2

                            All  First only  Third only
Consequences               41.4        24.4        23.3
Politics & policy          35.5        23.3        17.9
Trends and current status  26.5        18.4        13.4
Environmental problems     18.4         7.3        10.2
Solutions                  15.1         5.7         8.4
Carbon                     13.1         5.4         5.2
Individual behaviour       12.1         3.9         7.8
Energy                     11.2         6.0         7.5
Climate change denial       4.2         2.6         2.3
Activism                    4.1         0.9         2.8
Debate                      3.9         2.3         1.8
Nitrogen                    3.9         1.8         1.6
Agriculture                 3.1         0.9         2.1
Causes                      2.9         1.6         0.8
Transport                   2.6         0.5         1.8
Industry                    1.8         0.3         1.4
Climate change deniers      1.1         0.5         0.6

In [16]:
total = des.reset_index().join(des2.reset_index(), how='left', rsuffix='_cc')
total.to_latex(PATH+"/report/tables/sq_robustness.tex")
total

<ipython-input-16-5b4761fcfd34>:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  total.to_latex(PATH+"/report/tables/sq_robustness.tex")

,index,All,First only,Third only,index_cc,All_cc,First only_cc,Third only_cc
0,Admission,27.9,14.6,19.1,Consequences,41.4,24.4,23.3
1,Statistics,21.2,24.2,10.1,Politics & policy,35.5,23.3,17.9
2,Integration,14.6,10.5,8.4,Trends and current status,26.5,18.4,13.4
3,Accommodation center,12.3,4.5,7.4,Environmental problems,18.4,7.3,10.2
4,Causes,7.8,4.1,4.4,Solutions,15.1,5.7,8.4
5,Crime,6.5,3.3,3.6,Carbon,13.1,5.4,5.2
6,Politics,6.3,2.7,4.6,Individual behaviour,12.1,3.9,7.8
7,Origin,6.2,4.1,2.6,Energy,11.2,6.0,7.5
8,Housing,6.1,3.3,4.5,Climate change denial,4.2,2.6,2.3
9,Culture and religion,5.5,2.7,4.2,Activism,4.1,0.9,2.8
10,Problems,5.2,2.6,3.0,Debate,3.9,2.3,1.8
11,Economy,4.2,1.5,3.5,Nitrogen,3.9,1.8,1.6
12,Racism,3.6,3.3,2.3,Agriculture,3.1,0.9,2.1
13,Debate,3.4,3.0,2.1,Causes,2.9,1.6,0.8
14,Financial support,3.2,1.5,1.8,Transport,2.6,0.5,1.8
15,News,2.3,1.4,1.5,Industry,1.8,0.3,1.4
16,Vluchteling,33.2,12.5,13.4,Climate change deniers,1.1,0.5,0.6
17,Asielzoeker,27.9,12.1,10.3,NaN,NaN,NaN,NaN
18,Immigrant,27.5,16.9,9.8,NaN,NaN,NaN,NaN
19,Buitenlander,12.2,3.4,5.5,NaN,NaN,NaN,NaN
20,Allochtoon,6.7,3.0,2.1,NaN,NaN,NaN,NaN
21,Gelukszoeker,1.9,0.4,0.8,NaN,NaN,NaN,NaN
22,Statushouder,1.6,0.6,0.6,NaN,NaN,NaN,NaN
23,Expat,1.6,0.6,0.4,NaN,NaN,NaN,NaN