# 03b Calculating Intercoder reliability
Loading the annotated samples of two researchers and calcuating the Krippendorff's Alpha.
Some variables are dependent on others (see codebooks for more information), which has to be taken into account when calculating Krippendorff Alpha.

In [2]:
import pandas as pd
from datetime import datetime
import krippendorff
import numpy as np
date = datetime.now().strftime('%d%m%Y')

In [3]:
# setting paths
PATH = '/Users/marieke/SearchingForBias'

In [4]:
sample1 = pd.read_excel(PATH+"/data/climate/manual_coding/cc_MVH_ICR_02072021.xlsx", engine='openpyxl')
sample2 = pd.read_excel(PATH+"/data/climate/manual_coding/sq_cc_annotation_18062021_full_coded_TDV.xlsx", engine='openpyxl')

In [5]:
print(sample1.shape, sample2.shape)

(267, 25) (2671, 25)

In [6]:
# take the 10% sample out of full sample (TDV)
sample2 = sample2[sample2['search query'].isin(sample1['search query'])].copy()
sample2.shape

(267, 25)

In [7]:
sample1.set_index('search query', inplace=True)
sample2.set_index('search query', inplace=True)

In [8]:
sample1.head()

,GELDIG,SPECIFIEK,DISCUSSIE,INDIVIDUEEL_GEDRAG,VERVOER,INDUSTRIE,VOEDSELINDUSTRIE,STIKSTOF,CO2,ENERGIE,...,SCEPTICI_PERSONEN,GEVOLG,POLITIEK_BELEID,ACTIVISME,MILIEU,ONGECATEGORISEERD,EFFECTIEF,VRAAG,TAAL,Comments
search query,,,,,,,,,,,,,,,,,,,,,
ontwikkeling klimaat,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
alternatieve energie,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
grootste vervuilers,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
defensie,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
klimaatverdrag frankrijk hoe staat het er mee,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN

In [9]:
sample2.head()

,GELDIG,SPECIFIEK,INDIVIDUEEL_GEDRAG,VERVOER,INDUSTRIE,VOEDSELINDUSTRIE,STIKSTOF,CO2,ENERGIE,INFO_OPLOSSINGEN,...,GEVOLG,POLITIEK_BELEID,MILIEU,DISCUSSIE,ACTIVISME,ONGECATEGORISEERD,EFFECTIEF,VRAAG,TAAL,Comments
search query,,,,,,,,,,,,,,,,,,,,,
wat is de oorzaak van global warming,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN
informatie klimaat,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
uitsterven diersoorten klimaat,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
wappies,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
klimaatontwikkeling,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN

### 1. Calculation of ICR

In [10]:
def ICB_calculation(df1, df2, varname, conditional=None):
    tmpdf = pd.concat([df1[varname], df2[varname]], axis=1)
    if conditional:
        print('Conditional on...', conditional)
        index_conditional=pd.concat([df1[conditional], df2[conditional]], axis=1, keys=["MVH", "DT"]).query("MVH==1 & DT==1").index.to_list()
        tmpdf = tmpdf[tmpdf.index.isin(index_conditional)]
    matrix = np.array([tmpdf.iloc[:,0], tmpdf.iloc[:,1]])
    alpha = krippendorff.alpha(reliability_data=matrix, level_of_measurement='nominal')
    print(f'The intercoderreliability for {varname} is {alpha}')
    alpha = round(alpha, 3)
    return {varname:alpha}

In [11]:
# VALID
icr1 = ICB_calculation(sample1, sample2, 'GELDIG')

The intercoderreliability for GELDIG is 0.7715192043895748

In [12]:
varnames1 = ['SPECIFIEK', 'EFFECTIEF', 'VRAAG', 'TAAL']

In [13]:
icr2={}
for varname in varnames1:
    icr2.update(ICB_calculation(sample1, sample2, varname, conditional='GELDIG'))

Conditional on... GELDIG
The intercoderreliability for SPECIFIEK is 0.829382183908046
Conditional on... GELDIG
The intercoderreliability for EFFECTIEF is 0.8139443791617704
Conditional on... GELDIG
The intercoderreliability for VRAAG is 0.7936006320363421
Conditional on... GELDIG
The intercoderreliability for TAAL is 0.9313087490961678

In [14]:
varnames2=['INDIVIDUEEL_GEDRAG', 'VERVOER', 'INDUSTRIE', 'VOEDSELINDUSTRIE', 'STIKSTOF', 'CO2',
           'ENERGIE', 'INFO_OPLOSSINGEN', 'INFO_STATUS_QUO', 'OORZAKEN', 'SCEPTICI', 
           'SCEPTICI_PERSONEN', 'GEVOLG', 'POLITIEK_BELEID', 'MILIEU', 'DISCUSSIE', 'ACTIVISME']
           #'ONGECATEGORISEERD']

In [15]:
icr3={}
for varname in varnames2:
    icr3.update(ICB_calculation(sample1, sample2, varname, conditional='GELDIG'))

Conditional on... GELDIG
The intercoderreliability for INDIVIDUEEL_GEDRAG is 0.7840749414519906
Conditional on... GELDIG
The intercoderreliability for VERVOER is 0.9452298918854699
Conditional on... GELDIG
The intercoderreliability for INDUSTRIE is 0.8552590266875981
Conditional on... GELDIG
The intercoderreliability for VOEDSELINDUSTRIE is 1.0
Conditional on... GELDIG
The intercoderreliability for STIKSTOF is 1.0
Conditional on... GELDIG
The intercoderreliability for CO2 is 1.0
Conditional on... GELDIG
The intercoderreliability for ENERGIE is 0.9691535630645701
Conditional on... GELDIG
The intercoderreliability for INFO_OPLOSSINGEN is 0.8534181240063593
Conditional on... GELDIG
The intercoderreliability for INFO_STATUS_QUO is 0.7554376657824934
Conditional on... GELDIG
The intercoderreliability for OORZAKEN is 0.7415919282511211
Conditional on... GELDIG
The intercoderreliability for SCEPTICI is 0.7415919282511211
Conditional on... GELDIG
The intercoderreliability for SCEPTICI_PERSONEN is 1.0
Conditional on... GELDIG
The intercoderreliability for GEVOLG is 0.8667321924144311
Conditional on... GELDIG
The intercoderreliability for POLITIEK_BELEID is 0.8768696581196581
Conditional on... GELDIG
The intercoderreliability for MILIEU is 0.9198771797694224
Conditional on... GELDIG
The intercoderreliability for DISCUSSIE is 0.6652142338416849
Conditional on... GELDIG
The intercoderreliability for ACTIVISME is 0.8552590266875981

In [16]:
result = pd.DataFrame({**icr1, **icr2, **icr3}, index=["Krippendorff Alpha"]).T
result.to_latex(PATH+"/report/tables/climate/IRC_table.tex")
result

<ipython-input-16-1367b05154eb>:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  result.to_latex(PATH+"/report/tables/climate/IRC_table.tex")

                    Krippendorff Alpha
GELDIG                           0.772
SPECIFIEK                        0.829
EFFECTIEF                        0.814
VRAAG                            0.794
TAAL                             0.931
INDIVIDUEEL_GEDRAG               0.784
VERVOER                          0.945
INDUSTRIE                        0.855
VOEDSELINDUSTRIE                 1.000
STIKSTOF                         1.000
CO2                              1.000
ENERGIE                          0.969
INFO_OPLOSSINGEN                 0.853
INFO_STATUS_QUO                  0.755
OORZAKEN                         0.742
SCEPTICI                         0.742
SCEPTICI_PERSONEN                1.000
GEVOLG                           0.867
POLITIEK_BELEID                  0.877
MILIEU                           0.920
DISCUSSIE                        0.665
ACTIVISME                        0.855

In [17]:
sample1_n = sample1[[c for c in sample1.columns if c not in ['Comments']]].copy()
sample2_n = sample2[[c for c in sample2.columns if c not in ['Comments']]].copy()

In [18]:
#MVH
pd.DataFrame(sample1_n.apply(sample1_n.value_counts).T[1]) #.columns(['MVH'])

                    1.0
GELDIG              238
SPECIFIEK           232
DISCUSSIE             2
INDIVIDUEEL_GEDRAG   16
VERVOER               9
INDUSTRIE             4
VOEDSELINDUSTRIE      2
STIKSTOF              7
CO2                   8
ENERGIE              18
INFO_OPLOSSINGEN     20
INFO_STATUS_QUO      44
OORZAKEN              8
SCEPTICI              8
SCEPTICI_PERSONEN     1
GEVOLG               45
POLITIEK_BELEID      38
ACTIVISME             3
MILIEU               22
ONGECATEGORISEERD    14
EFFECTIEF           199
VRAAG                31
TAAL                  8

In [19]:
#TDV
pd.DataFrame(sample2_n.apply(sample2_n.value_counts).T[1])

                    1.0
GELDIG              248
SPECIFIEK           242
INDIVIDUEEL_GEDRAG   19
VERVOER              10
INDUSTRIE             3
VOEDSELINDUSTRIE      2
STIKSTOF              7
CO2                   8
ENERGIE              17
INFO_OPLOSSINGEN     17
INFO_STATUS_QUO      43
OORZAKEN              8
SCEPTICI             10
SCEPTICI_PERSONEN     1
GEVOLG               50
POLITIEK_BELEID      46
MILIEU               19
DISCUSSIE             1
ACTIVISME             4
ONGECATEGORISEERD     8
EFFECTIEF           209
VRAAG                31
TAAL                  7

### 2. Inspect disagreement

In [20]:
sample1.columns = [c+"_MVH" for c in sample1.columns]
sample2.columns = [c+"_TDV" for c in sample2.columns]

In [21]:
samples = pd.concat([sample1, sample2],axis=1)
samples = samples.reindex(sorted(samples.columns), axis=1)

In [22]:
#samples

In [23]:
varstotal=["GELDIG"]+varnames1+varnames2

In [24]:
disagreement = {}

In [25]:
filterdisagreements = samples.query('GELDIG_MVH!=GELDIG_TDV').index.to_list()
disagree = samples.loc[filterdisagreements,]
disagree = disagree[['GELDIG_MVH', 'GELDIG_TDV', 'Comments_TDV', 'Comments_MVH']]
disagreement.update({'GELDIG':disagree})

In [26]:
disagree

,GELDIG_MVH,GELDIG_TDV,Comments_TDV,Comments_MVH
search query,,,,
defensie,0,1,,NaN
methoden om mensen te manipuleren,0,1,NaN,NaN
veel te veel mensen in nederland,0,1,NaN,NaN
amerikaanse benadering,0,1,NaN,NaN
voor,0,1,NaN,NaN
leefklimaat,0,1,NaN,NaN
aankomendestemming in nederland,0,1,NaN,NaN
geitenwollen sokken geneuzel,0,1,NaN,NaN
wie zit er in de tweede kamer,0,1,NaN,NaN
politieke samenleving,0,1,NaN,NaN

In [27]:
for varname in varnames1:
    cols = [c for c in samples.columns if c.startswith(varname)]
    index_conditional=samples.query("GELDIG_MVH==1 & GELDIG_TDV==1").index.to_list()
    df = samples[samples.index.isin(index_conditional)]
    filterdisagreements = df.query(f'{cols[0]}!={cols[1]}').index.to_list()
    disagree = df.loc[filterdisagreements,]
    disagree = disagree[cols+['Comments_TDV', 'Comments_MVH']]
    disagreement.update({varname:disagree})

In [28]:
for varname in varnames2:
    cols = [c for c in samples.columns if c.startswith(varname)]
    index_conditional=samples.query("SPECIFIEK_MVH==1 & SPECIFIEK_TDV==1").index.to_list()
    df = samples[samples.index.isin(index_conditional)]
    filterdisagreements = df.query(f'{cols[0]}!={cols[1]}').index.to_list()
    disagree = df.loc[filterdisagreements,]
    disagree = disagree[cols+['Comments_TDV', 'Comments_MVH']]
    disagreement.update({varname:disagree})

In [29]:
disagree.columns

Index(['ACTIVISME_MVH', 'ACTIVISME_TDV', 'Comments_TDV', 'Comments_MVH'], dtype='object')

In [30]:
writer = pd.ExcelWriter(PATH+'/data/climate/manual_coding/ICR_disagreement.xlsx', engine='openpyxl')

In [31]:
for varname, df in disagreement.items():
    df.to_excel(writer, sheet_name=varname)

In [32]:
writer.save()